// The Master Database for cross-referencing AI results.
export const MASTER_FABRIC_DB: Record<string, string[]> = {
  "Alanis": ["Ash", "Beige", "Curry", "Dove", "Indigo", "Ivory", "Steel"],
  "Alba": ["Brick"],
  "Aria": ["Natural"],
  "Article": ["Ecru", "Ivory", "Mercury", "Moonstone", "Oyster", "Snow"],
  "Atlantis": ["Blue", "Charcoal", "Cloud", "Indigo", "Mineral", "Olive"],
  "Avalanche": ["Bone", "Ecru", "Flax", "Mushroom"],
  "Bali": ["Charcoal", "Linen", "Natural", "Navy", "Slate", "Smoke", "Snow"],
  "Belucci": ["Black", "Brick", "Ecru", "Fog", "Fossil", "Grey", "Metal", "Navy", "Ocean", "Olive", "Rose", "Serenity", "Steel"],
  "Bikendi": ["Black", "Cream", "Linen", "Zinc"],
  "Blend": ["Black", "Cobalt", "Flax", "Mineral", "Natural", "Teal"],
  "Bonta": ["Natural"],
  "BrightSide": ["Blue", "Carbon", "Chalk", "Dark Navy", "Grey"],
  "Canvas": ["Black", "Flax", "Grey", "Linen", "Straw", "White"],
  "Copenhagen": ["Charcoal", "Cream", "Latte", "Linen", "Natural", "Smoke", "Snow"],
  "Distraction": ["Domino", "Ecru", "Midnight", "Mocha", "Natural"],
  "Drill": ["Beige", "Charcoal", "Coffee", "Dark Grey", "Granite", "Latte", "Natural", "Pearl", "Platinum", "Slate"],
  "Dynamic": ["Ash", "Charcoal", "Snow", "Steel", "Taupe"],
  "Eclipse": ["Marble", "Platinum", "Cream", "Ebony", "Steel"],
  "Element": ["Cobalt", "Cocoa", "Dark Grey", "Emerald", "Grey", "Mustard", "Orange", "Poppy", "Stone", "Tusk", "Zinc"],
  "Elite": ["Dark Grey", "Flax", "Grey", "Pewter", "Royal", "Silver", "Spa", "Stone"],
  "Fancy": ["Bark", "Ivory", "Metal", "Mineral", "Pewter", "Tuks", "Zinc", "Brick", "Gold", "Steel"],
  "Farfalla": ["Grey"],
  "Fashion": ["Beige", "Black", "Bone", "Capuccino", "Grey", "Platinum", "Titanium"],
  "Fiora": ["Ash", "Choco", "Coral", "Ecru", "Grey", "Linen", "Pearl", "Soldier", "Spa", "Turquoise"],
  "Fiume": ["Midnight"],
  "Fly": ["Flax", "Nature", "Oyster", "Pewter"],
  "Forever": ["Chocolate", "Grey", "Midnight", "Moss", "Terra", "Alabaster", "Buttermilk", "Charcoal", "Curry", "Dove", "Parchment", "Walnut"],
  "Freedom": ["Granite", "Gravel", "Linen", "Sky", "Stone", "Turquoise"],
  "Fresh": ["Denim", "Flax"],
  "Galassia": ["Domino"],
  "Gellar": ["Cotton", "Jute", "Linen", "Marble"],
  "Harmony": ["Charcoal", "Coffee", "Cream", "Flax", "Grey", "Pearl", "Silver", "Taupe", "Titanium", "Ultramarine"],
  "Helsinki": ["Black", "Bone", "Domino", "Dove", "Onyx", "Stone", "Winter"],
  "HighLiving": ["Charcoal", "Linen", "Natural", "White"],
  "Isabella": ["Cream"],
  "Julietta": ["Linen"],
  "Kalahari": ["Baltic", "Champagne", "Eclipse", "Metal", "Mist", "Rose", "Sand", "Silver", "Sterling"],
  "Keten": ["Earth", "Natural", "Sand", "Tusk", "Smoke"],
  "Kiba": ["Domino", "Ebony", "Flaxen", "Linen", "Marble", "Mist", "Onyx", "Pool", "Quarry", "Rose", "Titanium"],
  "Lotus": ["Champagne", "Graphite", "Mica", "Red", "Silver"],
  "LoveMe": ["Black", "Cotton", "Sand", "Silver", "Stone"],
  "Lullaby": ["Bark", "Black", "Cream", "Fossil", "Ivory", "Mustard", "Olive", "Oyster", "Silver"],
  "Makar": ["Aqua", "Blueberry", "Canvas", "Galaxy", "Linen", "Rain", "Silver"],
  "Malibu": ["Bone", "Champagne", "Charcoal", "Cream", "Dark Grey", "Grey", "Ivory", "Snow"],
  "Merino": ["Charcoal", "Coconut", "Cotton", "Nickel", "Bone", "Desert", "Sand"],
  "Monique": ["Bluestone", "Cotton", "Domino", "Dove", "Ecru", "Pebble", "Porcelain", "Steel", "Twine"],
  "Monument": ["Beige", "Ecru", "Mica", "Mineral", "Silver", "Slate", "Smoke", "Stone"],
  "Nimbus": ["Ecru", "Natural", "Taupe"],
  "Niza": ["BLACK", "DARK GREY", "FOSSIL", "INDIGO", "MUSTARD", "SILVER", "SNOW"],
  "Nuvola": ["Snow"],
  "Odyssey": ["Fawn", "Jute", "Shell", "Smoke", "Steel"],
  "Orion": ["Nautical"],
  "Outrigger": ["Cream", "Ecru", "Pacific", "White"],
  "Oxford": ["Amber", "Baby Pink", "Beige", "Black", "Camel", "Cream", "Eclipse", "Fawn", "Fudge", "Grass", "Marine", "Mist", "Mocha", "Pewter", "Red Wine", "Snow", "Sterling", "Titanium", "Yellow"],
  "Presto": ["Charcoal", "Flax", "Stone"],
  "Prohibition": ["Ivory", "Pearl", "Snow"],
  "Reflect": ["Charcoal", "Dove", "Ecru", "Fossil", "Nature", "Snow", "Mystic Green", "Beige", "Cream", "Gold", "Silver", "Platinum"],
  "Rio": ["Ash", "Driftwood", "Graphite", "Salt", "Spinach"],
  "Ronda": ["Beige", "Blue", "Grey", "Ivory", "Mustard", "Sky", "Sliver", "Stone", "Taupe"],
  "Sahara": ["Blue Grey", "Celestial", "Flax", "Linen", "Opal", "Storm"],
  "Sapphire": ["Beige", "Bone", "Deepgrey", "Smoke", "Magenta", "Rose Quartz", "Serenity", "Blue", "Gold", "Orange", "Wine", "Persimon", "Green", "Black", "Silver Grey"],
  "Solid": ["Aquamarine", "Beige", "Bone", "Ebony", "Ivory", "Navy", "Olive", "Otter", "Rose", "Silver", "Snow", "Wood"],
  "Spectrum": ["Beige", "Deep Grey", "Dark Grey", "Hydro", "Ivory", "Ocean", "Steel"],
  "Tara": ["Cinnamon", "Cyan", "Dove", "Ebony", "Elephant", "Golden", "Olive", "Sand", "Sesame", "Snow", "Steel", "Wood"],
  "Tessa": ["Dove", "Ebony", "Ivory", "Khaki", "Midnight", "Oyster", "Shadow", "Vanilla"],
  "Toby": ["Cotton", "Fossil", "Marble", "Nature", "Porcelain", "Sable", "Twine"],
  "Topaz": ["Bittersweet", "Black", "Burlap", "Cream", "Greenery", "Iron", "Ocean"],
  "Venus": ["Blueberry", "Cameo", "Canvas", "Caviar", "Dolphin", "Hemp", "Oyster", "Rain"],
  "Victory": ["DarkGrey", "Grey", "Ivory", "Onyx", "Orion Blue", "Teal", "Yellow", "Thunder", "Beige", "Straw", "Capuchino", "Flint", "Sky"],
  "Vivacity": ["Aquamarine", "Beige", "Brick", "Chestnut", "Ebony", "Indigo", "Ivory", "Mustard", "Pine", "Shadow", "Snow"],
  "Waikiki": ["Denim", "Natural", "Pearl", "Snow"],
  "Wyatt": ["Cream", "Ebony", "Natural", "Nickel", "Porcelain", "Taupe"],
  "Zena": ["Denim", "Ebony", "Linen", "Natural", "Porcelain", "Putty", "Shadow", "Thunder", "Winter"],
  "Zenith": ["Aqua", "Black", "Brick", "Buttercup", "Cobalt", "Cocoa", "Emerald", "Grape", "Marine", "Mineral", "Natural", "Ocean", "Red", "Snow", "Stone", "Toffe", "Tusk", "Zinc", "Coral"]
};

// Start with an empty list as requested.
export const INITIAL_FABRICS = [];
