
import { Fabric, FurnitureTemplate } from './types';

// The Master Database for cross-referencing AI results.
export const MASTER_FABRIC_DB: Record<string, string[]> = {
  "Alanis": ["Ash", "Beige", "Curry", "Dove", "Indigo", "Ivory", "Steel"],
  "Alba": ["Brick"],
  "Alistair": ["Chalk", "Cloud", "Cotton", "Navy", "Nickel", "Sinatra", "Steel", "Sugar"],
  "Amadeo": ["Coal", "Flax", "Indigo"],
  "Amazon": ["Fog", "Mercury", "Zinc"],
  "Andreas": ["Linen"],
  "Angelo": ["Silver"],
  "Aria": ["Natural"],
  "Aries": ["Black", "Blush", "Charcoal", "Natural", "White"],
  "Article": ["Ecru", "Ivory", "Mercury", "Moonstone", "Oyster", "Snow"],
  "Asteri": ["Beige", "Eclipse", "Fawn", "Mocha", "Oxford", "Pewter", "Silver", "Steel", "White"],
  "Atlantis": ["Blue", "Charcoal", "Cloud", "Indigo", "Mineral", "Olive"],
  "Atlas": ["Dark Grey", "Demin", "Flame", "Grey", "Lavender", "Light Grey", "Marigold", "Midnight", "Snow", "Tuks"],
  "Avalanche": ["Bone", "Ecru", "Flax", "Mushroom"],
  "Babyboom": ["Beige"],
  "Bali": ["Charcoal", "Linen", "Natural", "Navy", "Slate", "Smoke", "Snow"],
  "Barce": ["Berry", "Bluebird", "Chocolate", "Gravel", "Grey", "Olive", "Pearl"],
  "Barletta": ["Garden", "Rose"],
  "Barrel": ["Aquamarine", "Black", "Bone", "Mustard", "Pine", "White"],
  "Basic": ["Gravel", "Ivory", "Silver"],
  "Beckon": ["Cement", "Indigo", "Metal", "Poppy", "Reed", "Salt", "Shell"],
  "Belgian": ["Cotton", "Flax", "Nickel"],
  "Bella": ["Turquoise"],
  "Belucci": ["Black", "Brick", "Ecru", "Fog", "Fossil", "Grey", "Metal", "Navy", "Ocean", "Olive", "Rose", "Serenity", "Steel"],
  "Bikendi": ["Black", "Cream", "Linen", "Zinc"],
  "Bizzy": ["Marble"],
  "Blend": ["Black", "Cobalt", "Flax", "Mineral", "Natural", "Teal"],
  "Bonta": ["Natural"],
  "Boon": ["Beige", "Iron Blue", "Onyx", "Steel", "White", "Zinc"],
  "Breton": ["Ivory", "Tusk", "Granite", "Cream"],
  "BrightSide": ["Blue", "Carbon", "Chalk", "Dark Navy", "Grey"],
  "Cannoli": ["Confetti"],
  "Canterbury": ["Mist", "Pewter"],
  "Canvas": ["Black", "Flax", "Grey", "Linen", "Straw", "White"],
  "Capadocia": ["Linen"],
  "Carosello": ["Ecru"],
  "Cascia": ["Blush", "Flax", "Porcelain"],
  "Champion": ["Latte"],
  "Chrono": ["Baby pink", "Black", "Brick", "Calypso", "Charcoal", "Cloud", "Gold", "Granite", "Grape", "Hydro", "Mint", "Moonstone", "Red", "Sand", "Seagreen", "Snow", "Spa", "True blue", "Wine"],
  "Clarity": ["Charcoal", "Slate Grey", "Smoke", "Toffe", "Desert"],
  "Contessa": ["Dove", "Oyster"],
  "Copenhagen": ["Charcoal", "Cream", "Latte", "Linen", "Natural", "Smoke", "Snow"],
  "Corbett": ["Coral", "Dune", "Fossil", "Ivory", "Latte", "Light Grey", "Mineral", "Oat", "Sage"],
  "Corsica": ["Amber", "Beige", "Blue", "Choco", "Coffee", "Domino", "Grey", "Red Brick", "Rose", "Spa"],
  "Cosmo": ["Dune", "Amber", "Autumn", "Griffin", "Marble", "Sabble", "Scuba", "Elephant", "Otter", "Taupe", "Sand"],
  "Cosse": ["Bone", "Natural", "Toffe"],
  "Dazzle": ["Cream", "Ebony", "Latte", "Nature"],
  "Distraction": ["Domino", "Ecru", "Midnight", "Mocha", "Natural"],
  "Dolly": ["Grey", "Natural", "Blue"],
  "Donna": ["Oat"],
  "Dreamy": ["Beige", "Domino", "Indigo", "Snow"],
  "Drill": ["Beige", "Charcoal", "Coffee", "Dark Grey", "Granite", "Latte", "Natural", "Pearl", "Platinum", "Slate"],
  "Duval": ["Beige", "Burlap", "Ecru", "Grey", "Iron", "Wood", "Sand"],
  "Dynamic": ["Ash", "Charcoal", "Snow", "Steel", "Taupe"],
  "Eclipse": ["Marble", "Platinum", "Cream", "Ebony", "Steel"],
  "Element": ["Cobalt", "Cocoa", "Dark Grey", "Emerald", "Grey", "Mustard", "Orange", "Poppy", "Stone", "Tusk", "Zinc"],
  "Elite": ["Dark Grey", "Flax", "Grey", "Pewter", "Royal", "Silver", "Spa", "Stone"],
  "Enigma": ["Beige", "Blue", "Capuccino", "Expresso", "Fossil", "Grey", "Iron", "Midnight", "Mustard", "Navy", "Smoke", "Zinc"],
  "Enora": ["Charcoal", "Cream", "Dark Grey", "Flax", "Grey", "Ivory", "Silver", "Black", "Brass", "Snow", "Indigo"],
  "Fancy": ["Bark", "Ivory", "Metal", "Mineral", "Pewter", "Tuks", "Zinc", "Brick", "Gold", "Steel"],
  "Farfalla": ["Grey"],
  "Fashion": ["Beige", "Black", "Bone", "Capuccino", "Grey", "Platinum", "Titanium"],
  "Favara": ["Cream"],
  "Fidelity": ["Godiva", "Golden", "Linen", "Platinum", "White"],
  "Fidenza": ["Bone", "Copper", "Grey", "Pearl", "Porcelain"],
  "Finn": ["Graphite", "Nickel"],
  "Fiora": ["Ash", "Choco", "Coral", "Ecru", "Grey", "Linen", "Pearl", "Soldier", "Spa", "Turquoise"],
  "Fiume": ["Midnight"],
  "Fly": ["Flax", "Nature", "Oyster", "Pewter"],
  "Forever": ["Chocolate", "Grey", "Midnight", "Moss", "Terra", "Alabaster", "Buttermilk", "Charcoal", "Curry", "Dove", "Parchment", "Walnut"],
  "Freedom": ["Granite", "Gravel", "Linen", "Sky", "Stone", "Turquoise"],
  "Fresh": ["Denim", "Flax"],
  "Fresno": ["Charcoal", "Oyster"],
  "Galassia": ["Domino"],
  "Gellar": ["Cotton", "Jute", "Linen", "Marble"],
  "Genova": ["BARK", "BLACK", "ELECTRIC BLUE", "MAUVE", "MERCURY", "MIDNIGTH", "NAVY", "SEAFOAM", "SEAGREEN", "SERENITY", "SILVER", "TOPAZ", "VINTAGE", "VIOLET", "WHITE"],
  "Giove": ["Curry"],
  "Glaze": ["Pewter"],
  "Glow": ["Cream", "Ebony", "Grey", "Ivory", "Nickel"],
  "Halsey": ["Mirage"],
  "Harmony": ["Charcoal", "Coffee", "Cream", "Flax", "Grey", "Pearl", "Silver", "Taupe", "Titanium", "Ultramarine"],
  "Heaven": ["Grey", "Lagoon", "Metal", "Pacific", "Storm"],
  "Helsinki": ["Black", "Bone", "Domino", "Dove", "Onyx", "Stone", "Winter"],
  "Heston": ["Cement", "Linen"],
  "HighLiving": ["Charcoal", "Linen", "Natural", "White"],
  "Highlight": ["Black", "Cloud", "Ivory", "Sand", "Silver"],
  "Icon": ["Darkgrey", "Dune", "Ecru", "Platinum", "Smokeblue", "White"],
  "Imperio": ["Shell", "Lilac", "Grape", "Ivory", "Tan", "Cobalt", "Navy", "Smoke Blue", "Camel", "Yellow", "Cinnabar", "Red"],
  "Indus": ["Beach", "Pumice"],
  "Inverno": ["Chalk", "Dove"],
  "Isabella": ["Cream"],
  "Julieta": ["Linen"],
  "Julietta": ["Linen"],
  "Kalahari": ["Baltic", "Champagne", "Eclipse", "Metal", "Mist", "Rose", "Sand", "Silver", "Sterling"],
  "Keten": ["Earth", "Natural", "Sand", "Tusk", "Smoke"],
  "Kiba": ["Domino", "Ebony", "Flaxen", "Linen", "Marble", "Mist", "Onyx", "Pool", "Quarry", "Rose", "Titanium"],
  "Kilburn": ["Pearl", "Zinc"],
  "Laramie": ["Steel"],
  "Livorno": ["Flax", "Mercury", "Pacific"],
  "Lotus": ["Champagne", "Graphite", "Mica", "Red", "Silver"],
  "LoveMe": ["Black", "Cotton", "Sand", "Silver", "Stone"],
  "Lucca": ["Ash", "Grey", "Latte", "Mustard", "Sand"],
  "Lullaby": ["Bark", "Black", "Cream", "Fossil", "Ivory", "Mustard", "Olive", "Oyster", "Silver"],
  "Lupatelli": ["Alabaster", "Fog", "Ink", "Marble", "Pearl"],
  "Magestic": ["Ash", "Fudge", "Granite", "Latte", "Platinum", "Steel", "Stone"],
  "Makar": ["Aqua", "Blueberry", "Canvas", "Galaxy", "Linen", "Rain", "Silver"],
  "Malibu": ["Bone", "Champagne", "Charcoal", "Cream", "Dark Grey", "Grey", "Ivory", "Snow"],
  "Marcus": ["Beige", "Onyx", "Platinum"],
  "Max": ["Linen"],
  "Merino": ["Charcoal", "Coconut", "Cotton", "Nickel", "Bone", "Desert", "Sand"],
  "Milan": ["Oyster"],
  "Mobility": ["Fawn", "Gravel", "Grey", "Latte", "Moonstone"],
  "Monello": ["Domino"],
  "Monet": ["Dove", "Ebony", "Navy", "Porcelain", "Snow"],
  "Monique": ["Bluestone", "Cotton", "Domino", "Dove", "Ecru", "Pebble", "Porcelain", "Steel", "Twine"],
  "Monument": ["Beige", "Ecru", "Mica", "Mineral", "Silver", "Slate", "Smoke", "Stone"],
  "Morgan": ["Bluegrey", "Dove", "Espresso", "Gravel", "Mercury", "Mindnight", "Sand"],
  "Mossa": ["Cotton"],
  "Mystery": ["Ash", "Charcoal", "Lagoon", "Latte", "Ocean"],
  "Nala": ["Black", "Iron", "Navy", "Sand", "Silver", "Snow"],
  "Napoles": ["Charcoal"],
  "Netherland": ["Taupe"],
  "Nimbus": ["Ecru", "Natural", "Taupe"],
  "Niza": ["BLACK", "DARK GREY", "FOSSIL", "INDIGO", "MUSTARD", "SILVER", "SNOW"],
  "Novara": ["Onyx"],
  "Nuvola": ["Snow"],
  "Ocala": ["Gravel", "Latte", "Pearl", "Teal", "Zinc"],
  "Odyssey": ["Fawn", "Jute", "Shell", "Smoke", "Steel"],
  "Omari": ["Natural"],
  "Opal": ["Amber", "Beige", "Camel", "Coral", "Cream", "Denim", "Flannel", "Fossil", "Grey", "Ivory", "Lagoon", "Olive", "Plum", "Silver", "Smoke", "Snow", "Steel"],
  "Opulence": ["Burnt Camel", "Camel", "Curry", "Ebony", "Snow", "Wheat"],
  "Orion": ["Nautical"],
  "Orso": ["Cream", "Ecru"],
  "Outrigger": ["Cream", "Ecru", "Pacific", "White"],
  "Oxford": ["Amber", "Baby Pink", "Beige", "Black", "Camel", "Cream", "Eclipse", "Fawn", "Fudge", "Grass", "Marine", "Mist", "Mocha", "Pewter", "Red Wine", "Snow", "Sterling", "Titanium", "Yellow"],
  "Paige": ["Sugar"],
  "Palermo": ["Cream"],
  "Passion": ["Hemp", "Java", "Linen", "Mineral", "Smoke"],
  "Pebble": ["Chalk", "Dove", "Platinum"],
  "Pier": ["Dove"],
  "Point": ["Admiral", "Camel", "Domino", "Dove", "Dune", "Grey", "Ivory", "Linen", "Pebble", "Pool", "Sky", "White"],
  "Popstar": ["Sand", "Snow", "Ecru"],
  "Prato": ["Beige"],
  "Prestige": ["Cream", "Ivory", "Natural", "Snow", "Tuxedo"],
  "Presto": ["Charcoal", "Flax", "Stone"],
  "Prohibition": ["Ivory", "Pearl", "Snow"],
  "Rayos": ["Ivory", "Moccasin", "Pewter", "Sugar", "Tan"],
  "Rhapsody": ["Kaleidoscope", "Placid Blue"],
  "Ricochet": ["Flax", "Natural"],
  "Rio": ["Ash", "Driftwood", "Graphite", "Salt", "Spinach"],
  "Romani": ["Sand", "Silver"],
  "Romeo": ["Bone"],
  "Ronda": ["Beige", "Blue", "Grey", "Ivory", "Mustard", "Sky", "Sliver", "Stone", "Taupe"],
  "Rumba": ["Metal", "Grey", "Natural", "Slate", "Wheat"],
  "Sahara": ["Blue Grey", "Celestial", "Flax", "Linen", "Opal", "Storm"],
  "Salvatore": ["Charcoal"],
  "Sante": ["Capuchino", "Grey"],
  "Sapphire": ["Beige", "Bone", "Deepgrey", "Smoke", "Magenta", "Rose Quartz", "Serenity", "Blue", "Gold", "Orange", "Wine", "Persimon", "Green", "Black", "Silver Grey"],
  "Sassari": ["Bone"],
  "Scottsdale": ["Indigo"],
  "Secret": ["Dove", "Gold", "Iron", "Navy", "Onyx", "Pine", "Sand", "Silver", "Snow", "Terra", "Wood"],
  "Shetland": ["Black", "Brick", "Grey", "Mist", "Mustard", "Natural"],
  "Sicilia": ["Nickel"],
  "Snowdon": ["Natural"],
  "Soho": ["Beige", "Ivory", "Metal", "Pewter", "Silver", "Smoke Blue", "Steel", "Taupe", "Toffee", "Mist", "Sand"],
  "Solid": ["Aquamarine", "Beige", "Bone", "Ebony", "Ivory", "Navy", "Olive", "Otter", "Rose", "Silver", "Snow", "Wood"],
  "Sorella": ["Pearl"],
  "Spark": ["Alabaster", "Beige", "Blossom", "Coffee", "Dune", "Earth", "Fog", "Ivory", "Linen", "Mercury", "Onyx", "Sand", "Zinc"],
  "Spectrum": ["Beige", "Deep Grey", "Dark Grey", "Hydro", "Ivory", "Ocean", "Steel"],
  "Spider": ["Capuchino"],
  "Stella": ["Buff", "Cobalt", "Latte", "Nickel", "Pacific", "Red", "Smoke"],
  "Sugarshack": ["Bone", "Denim", "Gravel", "Metal"],
  "Tara": ["Cinnamon", "Cyan", "Dove", "Ebony", "Elephant", "Golden", "Olive", "Sand", "Sesame", "Snow", "Steel", "Wood"],
  "Tessa": ["Dove", "Ebony", "Ivory", "Khaki", "Midnight", "Oyster", "Shadow", "Vanilla"],
  "Tiffany": ["Latte", "Mercury"],
  "Tigris": ["Bark", "Fog", "Kelp", "Salt"],
  "Titus": ["Chalk", "Pearl"],
  "TNT": ["Dark Blue", "Latte"],
  "Toby": ["Cotton", "Fossil", "Marble", "Nature", "Porcelain", "Sable", "Twine"],
  "Topaz": ["Bittersweet", "Black", "Burlap", "Cream", "Greenery", "Iron", "Ocean"],
  "Traffic": ["Alabaster", "Beige", "Dark Grey", "Mid Night", "Mink", "Smoke Blue"],
  "Trani": ["Ivory"],
  "Troy": ["Granite", "Sky", "Hemp", "Grey"],
  "Ultracover": ["Brown", "Indigo", "Khaki"],
  "Velvetglow": ["Emerald", "Tangerine", "Chocolate", "Khaki"],
  "Venus": ["Blueberry", "Cameo", "Canvas", "Caviar", "Dolphin", "Hemp", "Oyster", "Rain"],
  "Verona": ["Pepper", "Shell"],
  "Vicenza": ["Grey"],
  "Vicolo": ["Charcoal"],
  "Victory": ["DarkGrey", "Grey", "Ivory", "Onyx", "Orion Blue", "Teal", "Yellow", "Thunder", "Beige", "Straw", "Capuchino", "Flint", "Sky"],
  "Vittoria": ["Ecru"],
  "Vivacity": ["Aquamarine", "Beige", "Brick", "Chestnut", "Ebony", "Indigo", "Ivory", "Mustard", "Pine", "Shadow", "Snow"],
  "Waikiki": ["Denim", "Natural", "Pearl", "Snow"],
  "Whisper": ["Charcoal", "Pewter"],
  "Wyatt": ["Cream", "Ebony", "Natural", "Nickel", "Porcelain", "Taupe"],
  "Zappa": ["Amber", "Apple", "Burap", "Coconut", "Driftwood", "Ebony", "Espresso", "Fog", "Fossil", "Island", "Nature", "Nutmeg", "Raisin", "Sand", "Sinatra"],
  "Zena": ["Denim", "Ebony", "Linen", "Natural", "Porcelain", "Putty", "Shadow", "Thunder", "Winter"],
  "Zenith": ["Aqua", "Black", "Brick", "Buttercup", "Cobalt", "Cocoa", "Emerald", "Grape", "Marine", "Mineral", "Natural", "Ocean", "Red", "Snow", "Stone", "Toffe", "Tusk", "Zinc", "Coral"]
};

// Data of validated stock provided by the user
export const IN_STOCK_DB: Record<string, string[]> = {
  "Aberdin": ["Gris", "Lino", "Natural", "Oxford"],
  "Alanis": ["Ash", "Beige", "Ivory", "Steel"],
  "Alpino": ["Acero", "Arena", "Gris", "Marfil"],
  "Atlantis": ["Blue", "Charcoal", "Cloud", "Indigo", "Mineral", "Olive"],
  "Basket": ["Ash", "Beige", "Camel", "Graphite", "Grey", "Mocha", "Silver"],
  "Beckon": ["Cement", "Indigo", "Metal", "Poppy", "Reed", "Salt", "Shell"],
  "Belucci": ["Black", "Brick", "Ecru", "Fog", "Fossil", "Grey", "Metal", "Navy", "Ocean", "Olive", "Rose", "Serenity", "Steel"],
  "Blend": ["Black", "Cobalt", "Flax", "Mineral", "Natural", "Teal"],
  "Bloom": ["Black", "Chocolate", "Grey", "Mica", "Mustard", "Sand", "Smoke", "White"],
  "Cambridge": ["Beige", "Dove", "Olive", "Snow"],
  "Copenhagen": ["Charcoal", "Cream", "Latte", "Linen", "Natural", "Smoke", "Snow"],
  "Corsica": ["Amber", "Beige", "Blue", "Choco", "Coffee", "Domino", "Grey", "Red Brick", "Rose", "Spa"],
  "Distraction": ["Domino", "Midnight", "Mocha", "Natural"],
  "Doby": ["Aqua", "Azul", "Fresa", "Indigo", "Lavanda", "Lino", "Malva", "Manzana", "Marfil", "Marmol", "Menta", "Nuez", "Palo de Rosa", "Piedra", "Topo", "Turquesa"],
  "Drill": ["Beige", "Charcoal", "Coffee", "Darkgrey", "Granite", "Latte", "Natural", "Pearl", "Platinum", "Slate"],
  "Element": ["Cobalt", "Cocoa", "Darkgrey", "Emerald", "Grey", "Mustard", "Poppy", "Stone", "Tusk", "Zinc"],
  "Elite": ["Darkgrey", "Flax", "Grey", "Pewter", "Royal", "Silver", "Spa", "Stone"],
  "Enigma": ["Acero", "Aqua", "Beige", "Café", "Cereza", "Fossil", "Grey", "Iron", "Lavanda", "Marfil", "Marino", "Mink", "Mustard", "Natural", "Navy", "Oro", "Piedra", "Rey", "Rojo", "Topo", "Uva", "Verde", "Zinc"],
  "Enora": ["Cream", "Flax", "Grey", "Ivory", "Silver"],
  "Fancy": ["Bark", "Ivory", "Metal", "Mineral", "Pewter", "Tusk", "Zinc"],
  "Fashion": ["Beige", "Black", "Bone", "Capuchino", "Grey", "Platinum"],
  "Fiora": ["Ash", "Choco", "Coral", "Ecru", "Grey", "Linen", "Pearl", "Soldier", "Spa", "Turquoise"],
  "Freedom": ["Granite", "Gravel", "Linen", "Sky", "Stone", "Turquesa"],
  "Gellar": ["Jute", "Linen", "Marble"],
  "Genova": ["Bark", "Black Vintage", "Electric Blue", "Mauve", "Mercury", "Midnight", "Navy", "Seafoam", "Seagreen", "Serenity", "Silver", "Topaz", "Vintage", "Violet", "White"],
  "Harmony": ["Charcoal", "Coffee", "Cream", "Flax", "Grey", "Pearl", "Silver", "Taupe", "Titanium", "Ultramarine"],
  "High Living": ["Charcoal", "Linen", "Natural", "White"],
  "Holland Velvet": ["Beige", "Blush", "Deepgrey", "Emerald", "Lime", "Midnight", "Mocha", "Mustard", "Platinum", "Terracota", "Wine"],
  "Imperio": ["Camel", "Cinnabar", "Emerald", "Fudge", "Grey", "Lilac", "Smokeblue", "Tan", "Red", "Shell", "Yellow"],
  "Kalahari": ["Baltic", "Champagne", "Eclipse", "Metal", "Mist", "Rose", "Sand", "Silver", "Sterling"],
  "Kiba": ["Domino", "Ebony", "Flaxen", "Linen", "Mist", "Onix", "Pool", "Quarry", "Rose", "Titanium"],
  "Linus": ["Cement", "Charcoal", "Indigo", "Tomato"],
  "Lotus": ["Beige", "Blue", "Champagne", "Graphite", "Grey", "Mica", "Red", "Silver"],
  "Lullaby": ["Bark", "Black", "Cream", "Fossil", "Ivory", "Mustard", "Olive", "Oyster", "Silver"],
  "Maq Artell": ["Akron Beige", "Albany Azul", "Camel Aqua", "Camel Azafran", "Draco Cemento", "Draco Ceniza", "Silex Arena", "Silex Gris", "Silex Humo"],
  "Malibu": ["Bone", "Champagne", "Charcoal", "Cream", "Darkgrey", "Grey", "Ivory", "Snow"],
  "Monique": ["Bluestone", "Cotton", "Domino", "Dove", "Ecru", "Pebble", "Porcelain", "Steel", "Twine"],
  "Monument": ["Beige", "Ecru", "Mica", "Mineral", "Silver", "Slate", "Smoke", "Stone"],
  "Nude Beach": ["Apple", "Blue", "Carbon", "Dark Navy", "Grey", "Linen", "Navy", "Orange", "Overcast", "Sky", "Teal", "Yellow"],
  "Ocala": ["Gravel", "Latte", "Pearl", "Teal", "Zinc"],
  "Odyssey": ["Fawn", "Jute", "Shell", "Smoke", "Steel"],
  "Omni": ["Dove", "Ivory", "Sand"],
  "Outrigger": ["Cream", "Ecru", "Pacific", "White"],
  "Point": ["Admiral", "Camel", "Domino", "Dove", "Dune", "Grey", "Ivory", "Linen", "Pebble", "Pool", "Sky", "White"],
  "Presto": ["Charcoal", "Flax", "Stone"],
  "Prohibition": ["Ivory", "Pearl", "Snow"],
  "Reflect": ["Charcoal", "Dove", "Fossil", "Nature"],
  "Ronda": ["Beige", "Blue", "Grey", "Ivory", "Mustard", "Silver", "Sky", "Stone", "Taupe"],
  "Sahara": ["Bluegrey", "Celestial", "Flax", "Linen", "Opal", "Snow", "Storm"],
  "Sapphire": ["Beige", "Black", "Blue", "Bone", "Deepgrey", "Gold", "Green", "Magenta", "Orange", "Persimon", "Rosequartz", "Serenity", "Silvergrey", "Smoke", "Wine"],
  "Seaport": ["Charcoal", "Grey", "Sail"],
  "Shetland": ["Black", "Brick", "Grey", "Mist", "Mustard", "Natural"],
  "Siena": ["Black", "Ivory", "Light Grey", "Linen", "Navy", "Red Brick", "Rose"],
  "Soho": ["Beige", "Ivory", "Metal", "Pewter", "Silver", "Smokeblue", "Steel", "Taupe", "Toffe"],
  "Spark": ["Beige", "Bloosom", "Dune", "Linen", "Sand"],
  "Stella": ["Buff", "Cobalt", "Latte", "Nickel", "Orange", "Pacific", "Red", "Smoke"],
  "Sugarshack": ["Bone", "Denim", "Gravel", "Metal"],
  "Tessa": ["Dove", "Ebony", "Ivory", "Khaki", "Midnight", "Oyster", "Shadow", "Vanilla"],
  "Topaz": ["Bittersweet", "Black", "Burlap", "Cream", "Greenery", "Iron", "Ocean"],
  "Trixie": ["Charcoal", "Chocolate", "Indigo", "Linen", "Pewter", "Platinum", "Praline", "Sand"],
  "Turino": ["Ash", "Fog", "Linen", "Snow"],
  "Valentina": ["Ash", "Beige", "Copper", "Ferrari", "Royal", "Saddle", "Shark", "Taupe"],
  "Victory": ["Beige", "Capuchino", "Flint", "Grey", "Ivory", "Orion Blue", "Sky", "Straw", "Teal", "Thunder"],
  "Waikiki": ["Denim", "Natural", "Pearl", "Snow"],
  "Windsor": ["Bark", "Cream", "Ecru", "Latte", "Pewter"],
  "Zenith": ["Aqua", "Black", "Brick", "Buttercup", "Cobalt", "Cocoa", "Coral", "Emerald", "Grape", "Marine", "Mineral", "Natural", "Ocean", "Red", "Snow", "Stone", "Toffe", "Tusk", "Zinc"]
};

// Generamos la lista inicial automáticamente usando el Stock de Creata
// Esto asegura que si la app no tiene internet o la DB está vacía, se carguen estas telas.
export const INITIAL_FABRICS: Fabric[] = Object.entries(IN_STOCK_DB).map(([name, colors], index) => ({
  id: `stock-${index}-${Date.now()}`,
  name: name,
  supplier: 'CREATA STOCK',
  technicalSummary: 'Colección permanente en stock.',
  specs: { composition: 'N/A', martindale: 'N/A', usage: 'Tapicería General' },
  colors: colors,
  colorImages: {},
  mainImage: '', // Se mostrará el placeholder "Sin Foto" hasta que se carguen imágenes
  category: 'model'
}));

// Templates for the Visualizer
export const FURNITURE_TEMPLATES: FurnitureTemplate[] = [
  {
    id: 'sofa-01',
    name: 'Sofá Chesterfield',
    category: 'sofa',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=1770&q=80'
  },
  {
    id: 'chair-01',
    name: 'Silla Eames',
    category: 'chair',
    imageUrl: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80'
  },
  {
    id: 'armchair-01',
    name: 'Butaca Moderna',
    category: 'armchair',
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80'
  },
   {
    id: 'sofa-02',
    name: 'Sofá Minimalista',
    category: 'sofa',
    imageUrl: 'https://images.unsplash.com/photo-1550254478-ead40cc54513?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80'
  }
];
